//! GTK CSS: built-in fallback theme plus the optional user stylesheet
//! (generated by home-manager from the active stylix scheme).

use std::path::PathBuf;

use gtk4::gdk;

// Built-in fallback palette. These @define-color names are what the layout
// references; the user stylesheet (see load) can redefine any of them to theme
// waycal — e.g. generated from a stylix base16 scheme.
const COLOR_DEFAULTS: &str = r#"
@define-color waycal_bg #1a2125;
@define-color waycal_fg #c9d1d9;
@define-color waycal_dim #6a7a71;
@define-color waycal_accent #8FBC8F;
@define-color waycal_accent_fg #1a2125;
"#;

// Layout and non-color styling. font-family/font-size on .waycal-root are only
// fallbacks: the stylix-generated user stylesheet overrides both so the popup
// tracks the desktop's monospace font and `popups` size. Everything else is
// sized in `em`, so it scales with whatever root font-size wins — only
// spacing/borders stay in px since stylix doesn't define those.
const LAYOUT: &str = r#"
window.waycal {
    background: transparent;
}
.waycal-root {
    background-color: @waycal_bg;
    border: 2px solid @waycal_accent;
    border-radius: 0;
    padding: 14px 18px;
    color: @waycal_fg;
    font-family: monospace;
    font-size: 12pt;
    min-width: 260px;
}
.waycal-header {
    font-weight: bold;
    font-size: 1.15em;
    padding-bottom: 6px;
}
.waycal-weekday {
    color: @waycal_accent;
    font-weight: bold;
    padding: 2px 6px;
}
.waycal-day {
    padding: 4px 7px;
    min-width: 18px;
}
.waycal-day.dim {
    opacity: 0.3;
}
.waycal-day.today {
    color: @waycal_accent;
    font-weight: bold;
}
/* The keyboard cursor: a filled highlight that moves day-to-day. */
.waycal-day.selected {
    background-color: @waycal_accent;
    color: @waycal_accent_fg;
    border-radius: 0;
    font-weight: bold;
}
.waycal-footer {
    color: @waycal_dim;
    font-size: 0.72em;
    padding-top: 8px;
    margin-top: 6px;
    border-top: 1px solid alpha(@waycal_accent, 0.18);
}
"#;

fn user_style_path() -> Option<PathBuf> {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))?;
    Some(base.join("waycal").join("style.css"))
}

/// Build the stylesheet and install it on the default display.
pub fn load() {
    // Order matters, all within one deterministic provider:
    //   1. COLOR_DEFAULTS — fallback @define-color values.
    //   2. LAYOUT — structure + fallback font, referencing those color names.
    //   3. user file (stylix) — LAST, so it wins twice over: its @define-color
    //      redefinitions override the defaults (last definition wins, and color
    //      references resolve against the final map), and its `.waycal-root`
    //      font rule overrides LAYOUT's fallback (equal specificity, later wins).
    let mut css = String::from(COLOR_DEFAULTS);
    css.push_str(LAYOUT);
    if let Some(user) = user_style_path().and_then(|p| std::fs::read_to_string(p).ok()) {
        css.push_str(&user);
    }

    let provider = gtk4::CssProvider::new();
    provider.load_from_string(&css);
    if let Some(display) = gdk::Display::default() {
        gtk4::style_context_add_provider_for_display(
            &display,
            &provider,
            gtk4::STYLE_PROVIDER_PRIORITY_APPLICATION,
        );
    }
}
